[package]
name = "ntuple"
version = "0.4.1"
edition = "2021"

[dependencies]
hepmc2 = { version = "0.5", optional = true }
thiserror = "1.0"

[build-dependencies]
anyhow = "1.0"
bindgen = "0.60"
cc = "1.0"

[dev-dependencies]
tempfile = "3.3"
